#Database common configurations
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=*

test.message=In-application
